### ISSUE TITLE
Streaming raspiraw to PC

### ISSUE THREAD

**Issue by wx405557858** [6by9/raspiraw#26]
Is it possible to stream the raspiraw to other computational powerful devices to do real-time perception?

**Comment by 6by9** [comment]
Many things are possible, but I doubt this one is practical due to bandwidth.

MIPI CSI2 can run at up to 1Gbit/s per data lane, and up to 4 lanes. 4Gbit/s of data isn't practical to send over USB2, and the network interface even on the Pi3B+ is over that.
You don't say what source you are intending to use, but 8MPix @ 15fps from imx219 would be 1.21Gbit/s. Even 1080P30 will be 622Mbit/s.

You'd be far better off interfacing your CSI2 source directly to your more powerful device if you can.
