### ISSUE TITLE
Installation instructions and why does it not work?

### ISSUE THREAD

**Issue by nabbl** [6by9/raspiraw#7]
It would be great to have actual installation instructions for the different cameras/boards and so on. Currently you need to search in 4 different raspi threads to get it working.

I tried installing it by following these steps:
https://www.raspberrypi.org/forums/viewtopic.php?f=43&t=189661&p=1232058#p1218763
and cloning this repository instead of the download which is in the instructions above.

But I still don't seem to get it working correctly. Images captured are completely white. Before updating the PI software there were just some small blue bars captured.

I use a Raspberry Pi B Rev 2.1 and a raspi cam v2.

Tried to use any of the tools. But can't seem to be able to capture a single good frame.

Thanks for your help :)

**Comment by nabbl** [comment]
Thank you for helping.

When I type ./camera_i2c:
```
setting GPIO for board revsion: 000e
B Rev2 - I2C 0 on GPIOs 0 & 1. GPIOs 5 & 21 for LED and power
```

Running raspivid first didn't really fix anything. I can take perfect videos and photos using raspivid and raspistill.

I have tried all your suggestions. I assume I kind of botched my installation.

**Comment by nsimon1** [comment]
@nabbl Unfortunately I do not have your board revision to try it out and see the exact output. I do see that your revision is in the [script](https://github.com/6by9/raspiraw/blob/master/camera_i2c#L28), so it should be setting up the pins correctly. 

As a side note: It seems that you may not get that table output for every board, so it might not apply to this case.  

I would double check on the forums to see if anybody else has tried with a model B board.  

I believe those errors are just from the [cleaning up section](https://github.com/6by9/raspiraw/blob/master/raspiraw.c#L1406) of the program and your error must be happening before that.  

Did you not get any output on the screen connected to the raspberry?

**Comment by jacobhuesman** [comment]
If you're having trouble with this library, a potential alternative is https://github.com/cedricve/raspicam. I'm not advocating one over the other, I've just used it a project before and didn't have much trouble getting it up and running.

**Comment by nabbl** [comment]
Thank you jacobhuesman. That one looks promising. I need the camera to capture in 300-600fps though. I don't know if I will manage to do this with raspicam lib.
In the readme however I found the source of my errormessages above (port is not enabled). Need to increase the gpu RAM.

Is it really necessary to install the userland repo completely in order to get  raspiraw running?

**Comment by 6by9** [comment]
https://github.com/cedricve/raspicam is using the standard camera stack, so you won't get frame rates above 120fps.

raspiraw is only meant as a starting point, not a fully fledged app. If you don't understand at least some of the detail of what is going on then you will be in a world of pain, and everything is set up to be fully manual control (probably explains your fully white images to start with - it is running, but totally saturated). 
And please remember that the images off the sensor will be the raw Bayer images and therefore probably in need of some processing to make them useful.

I'm a little surprised that you needed to increase GPU mem if you had raspistill/vid working. Enabling the camera in raspi-config normally increases GPU mem to 128, which should be more than sufficient for raspiraw.

As long as the installed userland is reasonably up to date, then there is no need to clone and build it yourself. I'm guessing you're tripping over old instructions where the raspiraw app was in a fork of the userland repo, but now it is out in this repo by itself.

```mmal_port_disable``` error message hopefully fixed with the latest push.
Please always provide the full text including the command when reporting issues, and preferably report on any delays between lines of text (eg 5 seconds from starting the command to those error messages would have told me that it had run and waited the default timeout). I'm making an educated guess as to how you're using raspiraw.
As surmised it's only the clean up code which is trying to disable a port that had already been disabled when not capturing.

@nsimon1 Any objections if I lift your comment above with minor edits and stick it into README.md as installation instructions? You've done a pretty good job at covering everything so I'd only be rehashing it to write my own.

**Comment by nsimon1** [comment]
@6by9 No objections, use whatever you can, thanks!

**Comment by nabbl** [comment]
Hey there.

Was able to make a complete reset of my pi and use the installation instructions from @nsimon1 

I am now able to take good looking fotos. Thx a lot :)
